name: Welcome newbie

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
         script: |
            const issue = context.payload.issue;
            const username = issue.user.login;
            const greetingMessage = `Привет, @${username}!`;
            
            await github.issues.createComment({
              ...context.repo,
              issue_number: issue.number,
              body: greetingMessage
            });
