name: Welcome newbie

on:
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome newbie
        uses: actions/github-script@v5
        with:
          script: |
            const issue = context.payload.issue;
            const username = issue.user.login;
            const greetingMessage = `Привет, @${username}!`;
            
            await github.issues.createComment({
              ...context.repo,
              issue_number: issue.number,
              body: greetingMessage
            });
